image: node:12.1.0
cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

before_script:
  - npm install

test_code:
  stage: test
  script:
    - npm run lint

deploy_stage:
  stage: deploy
  environment:
    name: stage
    url: beta-server.adally.com
  only:
    - stage

  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$STAGE_RSA_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$STAGE_RSA_PRIVATE_KEY" > ./key
    - chmod 600 ./key
  script:
    - ssh -o "StrictHostKeyChecking=no" -i ./key $SERVER_USERNAME@$STAGE_DNS "cd $PROJECT_DIR_LOCATION; git checkout stage; git reset --hard; git clean -fd; git pull; npm run build; docker-compose up --build -d; docker system prune -a --volumes -f"

deploy_prod:
  stage: deploy
  environment:
    name: prod
    url: beta-server.adally.com
  only:
    - master

  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$PROD_RSA_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$PROD_RSA_PRIVATE_KEY" > ./key
    - chmod 600 ./key

  script:
    - ssh -o "StrictHostKeyChecking=no" -i ./key $SERVER_USERNAME@$PROD_DNS "cd $PROJECT_DIR_LOCATION; git checkout stage; git reset --hard; git clean -fd; git pull; npm run build; docker-compose up --build -d; docker system prune -a --volumes -f"
