version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.${ENV}
    container_name: server
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - /adally-server/node_modules
      - .:/adally-server
  mongo:
    container_name: server-mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
