FROM node:alpine

RUN apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python git && \
  npm install --quiet node-gyp -g

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

RUN mkdir config
RUN mkdir config/typescript
COPY ./config/typescript/tsconfig.json ./config/typescript/tsconfig.json

COPY . .

RUN npm run build
COPY ./config/scripts/stage/. ./dist/scripts/.

CMD ["npm", "run", "start"]
